### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by distintiva**
To add new interesting software based on Scratch to program micro:bit,   and a new micro:bit library with many features

### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

- [x] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [x] I am making an individual pull request for each suggestion
- [x] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [x] The content linked is in English, or it contains an English translation
- [x] I have added the new entry to the bottom of its the category
- [x] I have used the following format:
```
- [Resource Title](link) - Resource short Description (2 lines or less in total)
```

### CODE REVIEW

**Comment by carlosperate** [comment]
Thanks for the submission, these are great!

When I merge the PR the https://twitter.com/awesomemicrobit account will automatically create a tweet with the link. Since this PR contains two entries, the twitter bot will only tweet the first one (which is not a problem), but if you prefer to separate one of the entries into a different PR I'd be happy to merge both so that it creates a tweet for each one.
What do you prefer?

**Comment by carlosperate** [comment]
Hi @distintiva, do you have any thoughts on my last comment?

**Comment by distintiva** [comment]
Sorry Carlos
I didn't view your last message.
You can merge both entries in one PR, no problem, and tweet only first one

**Comment by carlosperate** [comment]
I forgot I updated the script to tweet all the entries on the PR, so in the end both tweets were sent: 
- https://twitter.com/awesomemicrobit/status/1233030201484992513
- https://twitter.com/awesomemicrobit/status/1233030200163807233

**Pull request merged**
