### PR TITLE
SBrickPlus option to the list of resources

### PR DESCRIPTION
**Pull request by Salva-OA**
A BLE link from Microbit to the SBrickPlus 4 ports Hub, of 4 pins (Vcc, gnd, C1, C2) where we can have power-function Lego motors (dc and servo), plus analog sensors (Lego wedo1 infrared light distance sensor, Lego wedo1 tilt sensor or others acording to these examples:

             https://ofalcao.pt/blog/2014/lego-wedo-temperature-sensor
             https://picaxe.com/teaching/other-software/scratch-helper-apps/  
             https://www.youtube.com/watch?v=zH2cT7tV_qA )

Document about Hub and Microbit link for Makecode enviroment:
https://docs.google.com/presentation/d/e/2PACX-1vQzjpJyqFFxas5k2gr7jl-WhsK3yGuV0Pw9a0OA6kjgGGKZJTHUTWr9VG8Fa6J8CtY3PCKeRGEuPesd/pub?start=false&loop=false&delayms=60000&slide=id.g3264c53747_0_9

The Typescript code repository:  https://github.com/vengit/pxt-sbrick, 

Through the study of their https://social.sbrick.com/custom/The_SBrick_BLE_Protocol.pdf it might be possible to adapt it to other coding languages.

### CODE REVIEW

**Review by carlosperate — CHANGES_REQUESTED** [review]
Hi @Salva-OA, thanks for the submission!

I think something is not quite right with the PR, this has been created to merge the `master` branch into the `restore-1` branch, both of wich are branches in this repository.

Normally you create a PR from a branch in your fork, hopefully these instructions should help: https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md#adding-something-to-an-awesome-list

**Comment by Salva-OA** [comment]
ok, sorry

**Comment by carlosperate** [comment]
No worries, let me know if you need a hand creating the PR and don't hesistate to ask any questions 👍

**Comment by carlosperate** [comment]
I'll close this as it will trigger notifications to repo watchers every time there is a commit in this repo. But please, do reopen a PR with those entries if you'd like to add them to the list, thanks!

**Pull request closed without merging**
