### PR TITLE
Add TCS3200

### PR DESCRIPTION
**Pull request by alankrantas**
### By submitting this pull request I confirm I've read and complied with the below requirements 🖖

- [ ] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-microbit/blob/master/contributing.md)
- [ ] I am making an individual pull request for each suggestion
- [ ] I have used the correct spelling and capitalisation for `BBC micro:bit`, `micro:bit`, and `Micro:bit Educational Foundation` (resource title could be excluded if there is a good reason)
- [ ] The content linked is in English, or it contains an English translation
- [ ] I have added the new entry to the bottom of its the category
- [ ] I have used the following format:
```
- [Resource Title](link) - Resource short Description (2 lines or less in total)
```

### CODE REVIEW

**Comment by carlosperate** [comment]
Thanks for the submission @alankrantas.
There are 2 entries here and the title only refers to one, did you mean to do that?
If you add more commits to the same branch they will appear in the same PR, so just letting you know in case you were not aware.

**Comment by alankrantas** [comment]
Yeah, I thought it would be seperated (for the next PR).

Do I need to revert (or change it by another commit) the second one?

**Comment by carlosperate** [comment]
You can create a new branch from 44e6809, submit that as a PR. Then I can merge that PR first and then this one.

I would recommend to do this:
- Create a new branch from your current master branch
- Create a new branch at the 44e6809 commit (the one that only contains the TCS3200 entry)
- Submit a PR with the TCS3200 entry only

```
git checkout master
git checkout -b ir
git checkout 44e68099965b4e1d26c7d373983bbe270afe6b24
git checkout -b tcs
git push origin tcs
```

At this point you can submit the `tcs` branch as a new PR.

If you want to submit the ir branch as a new PR that is fine as well, we could then close this one, but that is not necessary.

And then **after** I merge both PRs you can do the following to restore the master branch to be the same as this repository master branch (it basically deletes your master and replaces it with the same master as my repository):
```
git remote add upstream https://github.com/carlosperate/awesome-microbit.git
git fetch upstream 
git checkout ir
git branch -D master
git checkout -b master upstream/master
```

**Comment by alankrantas** [comment]
Sorry, but it's becoming a bit too complicated for me.

I'm not a proper trained software engineer, and I know next to nothing about git. A year ago I hadn't heard about micro:bit, Arduino or any MCUs. I do everything directly on Github and MakeCode.

How about I scratched my forked repository and close this PR and start over?

**Comment by carlosperate** [comment]
Sure, no problem, that works for me.

Quick tip, instead of editing the README file in the "master" branch, you can create new branches on GitHub using this field:

image

You can type the name of the branch and then click on "create branch: xxxx" :)

**Pull request closed without merging**
