### PR TITLE
Add S2Bot Scratch Programming Tool.

### PR DESCRIPTION
**Pull request by manchoz**

### CODE REVIEW

**Comment by carlosperate** [comment]
Thanks @manchoz! Sorry for the delay in checking this out, I was away on holiday :)
Quick question before I merge, is that specific dongle required for this to work? Wouldn't any bluetooth connection be fine?

**Comment by manchoz** [comment]
Hi @carlosperate, yes, S2Bot would work only with Silicon Labs BLED112 dongle.

This dongle is not a proper Bluetooth (LE) dongle, it is more an (USB) host device with a BlueGiga BLE chip on board. PC talks to BLED112 via UART or with BlueGiga's Smart Software SDK or BGScript.

S2Bot creates a Scratch Extension endpoint and relays requests/responses to/from micro:bit via BLED112. You alse need to load a Picaxe-provided  firmware to micro:bit in order to connect (no pairing required) and to understand the S2Bot protocol.

I think that would be not to difficult to implement a similar solution working with generic BLE dongles, maybe using [Bluepy](https://github.com/IanHarvey/bluepy) or [Able](https://github.com/sandeepmistry/noble) or [Gatt](https://github.com/paypal/gatt).

Bye!

**Comment by carlosperate** [comment]
Thanks for the clarification, I'll merge it.

**Comment by manchoz** [comment]
Thank you!
I received a couple of BLED112 few days ago and I confirm that they works great with Scratch 2 and BBC micro:bit. Setup is pretty simple but, to date, there is only a limited subset of micro:bit special features that are supported by s2bot.

**Comment by carlosperate** [comment]
I'm glad you can confirm it works :)

**Pull request merged**
