### PR TITLE
[DE] Added OneDay-Presentation for GirlsDay 2018

### PR DESCRIPTION
**Pull request by stritti**
I created a presentation for upcoming GirlsDay in German using impress.js

### CODE REVIEW

**Comment by carlosperate** [comment]
Thanks a lot for the submission!
Except for the community section I try to keep all the links in English, do you have an English version of the resource we could link to?

**Comment by stritti** [comment]
Sorry there is no English version. It is especially for German girls created. I want to lower the level for the girls not to add all in English from beginning.

**Comment by carlosperate** [comment]
I completely understand, it makes perfect sense to have it in your local language, and I am really happy to see you've done a micro:bit workshop for GirlsDay!
However, I think at the moment I will only include resources in English, as that's the language the majorit of the visitors would expect, and a language that I can personally understand as well.
Have you shared the workshop on social media already? Even if I don't include it in this list, I'd love to share it on twitter if that's okay with you.

**Comment by stritti** [comment]
Okay, I see.
I have not known, that the list is limited to English content.

I have not promoted the content yet but will do it after Girl's Day on Thursday.

**Pull request closed without merging**
